# version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./client/ssl.crt:/etc/nginx/ssl.crt:ro
      - ./client/ssl_private.key:/etc/nginx/ssl_private.key:ro
    networks:
      - user-facing
      - back-office
    depends_on:
      - backend

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: ropa
    ports: []
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back-office

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: []
    networks:
      - back-office

networks:
  user-facing:
  back-office:

volumes:
  postgres_data:
